SosAnimauxFront\FrontOfficeBundle\Entity\Adherant:
    type: entity
    table: adherant
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
        prenom:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
        email:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
        mdp:
            type: string
            nullable: true
            length: 50
            fixed: false
            comment: ''
        telephone:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
        ville:
            type: string
            nullable: true
            length: 20
            fixed: false
            comment: ''
        adresse:
            type: string
            nullable: true
            length: 30
            fixed: false
            comment: ''
        age:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
        sexe:
            type: string
            nullable: false
            length: 10
            fixed: false
            comment: ''
        photo:
            type: blob
            nullable: true
            length: null
            fixed: false
            comment: ''
        photourl:
            type: string
            nullable: true
            length: 250
            fixed: false
            comment: ''
        etat:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '1'
    lifecycleCallbacks: {  }
