SosAnimauxFront\FrontOfficeBundle\Entity\Admin:
    type: entity
    table: admin
    id:
        login:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        mdp:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
