parameters:
#    front_office.example.class: SosAnimauxFront\FrontOfficeBundle\Example

services:
#    front_office.example:
#        class: %front_office.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
